language: php
php:
  - 7

before_install:
  - pecl install pthreads
  - echo "extension=pthreads.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
install:
  - composer install --prefer-source --dev
script:
  - phpunit

matrix:
  fast_finish: true
notifications:
  webhooks: http://zerglinggo.net/travis/notification
