language: php
php:
  - 7
install:
  - composer install --prefer-source --dev
before_script:
  - wget https://pecl.php.net/get/pthreads-3.1.4.tgz -O pthreads.tgz
  - tar xvzf pthreads.tgz && cd pthreads && phpize && ./configure && make install && cd ..
  - echo "extension=pthreads.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
script:
  - phpunit

matrix:
  fast_finish: true
notifications:
  webhooks: http://zerglinggo.net/travis/notification
